In [1]:
import numpy as np

C:\MySoftware\Anaconda3\envs\cv1\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\MySoftware\Anaconda3\envs\cv1\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\MySoftware\Anaconda3\envs\cv1\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
A = np.array([[1, 1], [2, 2], [0, 0]])
U, S, V = np.linalg.svd(A)
print(U)
print(S)
print(V)

[[-0.4472136  -0.89442719  0.        ]
 [-0.89442719  0.4472136   0.        ]
 [ 0.          0.          1.        ]]
[3.16227766e+00 1.57009246e-16]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [3]:
from sklearn.utils.extmath import randomized_svd

In [4]:
U, S, V = randomized_svd(A, n_components=2)
print(U)
print(S)
print(V)

[[ 0.4472136   0.89442719]
 [ 0.89442719 -0.4472136 ]
 [ 0.         -0.        ]]
[3.16227766e+00 1.62596948e-32]
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


C:\MySoftware\Anaconda3\envs\cv1\lib\site-packages\sklearn\utils\extmath.py:368: FutureWarning: If 'random_state' is not supplied, the current default is to use 0 as a fixed seed. This will change to  None in version 1.2 leading to non-deterministic results that better reflect nature of the randomized_svd solver. If you want to silence this warning, set 'random_state' to an integer seed or to None explicitly depending if you want your code to be deterministic or not.
  warnings.warn(


In [5]:
from sklearn.decomposition import PCA

In [6]:
X = np.random.randn(100, 3)
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)
print(X_pca.shape)

(100, 2)
